services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    volumes:
      - ./.docker/etc/otelcol-contrib/config.yaml:/etc/otelcol-contrib/config.yaml
    command:
      - "--config"
      - "/etc/otelcol-contrib/config.yaml"
    ports:
      - 4317:4317
      - 8889:8889
    depends_on:
      - jaeger

  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./.docker/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss:11.4.0
    container_name: grafana
    user: "$UID:$GID"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - TZ=America/Sao_Paulo
    volumes:
      - ./.docker/grafana:/var/lib/grafana
    ports:
      - 3000:3000

  jaeger:
    image: jaegertracing/all-in-one:1.64.0
    container_name: jaeger
    ports:
      - 16686:16686
      - 14268
      - 14250

  dcs-postgres:
    image: postgres:17.2-alpine3.21
    container_name: dcs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: Melon@123
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
